{% set name = "nr.util" %}
{% set version = "0.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nr.util-{{ version }}.tar.gz
  sha256: d27e07755d7bc4c3adc042c9e792cdd1b03b9b85cde55a95068ebd4c37729f9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - deprecated >=1.2.0,<2.0.0
    - python >=3.7
    - typing-extensions >=3.0.0

test:
  imports:
    - nr.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NiklasRosenstein/python-nr.util
  summary: General purpose Python utility library.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NiklasRosenstein
